repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.3
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/uktrade/github-standards
    rev: v1.4.1 # This should be the latest github released tag, see https://github.com/uktrade/github-standards/releases for the latest tag
    hooks:
      - id: validate-security-scan
        verbose: false # This is helpful for debugging initial setup, it can be removed when the hooks are verified as working in your repository
        args: [-v] # This is helpful for debugging the hook logic, the output is shown in the git output
      - id: run-security-scan
        verbose: false
        args: [--verbose]
